// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `cities` table.
    ///
    /// (Automatically generated by Diesel.)
    cities (id) {
        /// The `id` column of the `cities` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `user_id` column of the `cities` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Integer>,
        /// The `city_name` column of the `cities` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        city_name -> Varchar,
        /// The `is_single_model` column of the `cities` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        is_single_model -> Nullable<Bool>,
        /// The `model_path` column of the `cities` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        model_path -> Nullable<Varchar>,
        /// The `svg_height` column of the `cities` table.
        ///
        /// Its SQL type is `Nullable<Float>`.
        ///
        /// (Automatically generated by Diesel.)
        svg_height -> Nullable<Float>,
        /// The `svg_width` column of the `cities` table.
        ///
        /// Its SQL type is `Nullable<Float>`.
        ///
        /// (Automatically generated by Diesel.)
        svg_width -> Nullable<Float>,
    }
}

diesel::table! {
    /// Representation of the `files` table.
    ///
    /// (Automatically generated by Diesel.)
    files (file_id) {
        /// The `file_id` column of the `files` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        file_id -> Integer,
        /// The `user_id` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Integer>,
        /// The `path` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        path -> Nullable<Varchar>,
        /// The `file_type` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        file_type -> Nullable<Varchar>,
        /// The `size` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Bigint>`.
        ///
        /// (Automatically generated by Diesel.)
        size -> Nullable<Bigint>,
        /// The `created_at` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Nullable<Timestamp>,
        /// The `updated_at` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Timestamp>,
        /// The `permissions` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 100]
        permissions -> Nullable<Varchar>,
    }
}

diesel::table! {
    /// Representation of the `images` table.
    ///
    /// (Automatically generated by Diesel.)
    images (image_id) {
        /// The `image_id` column of the `images` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        image_id -> Integer,
        /// The `image_path` column of the `images` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        image_path -> Nullable<Varchar>,
        /// The `user_id` column of the `images` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Integer>,
        /// The `city_id` column of the `images` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        city_id -> Nullable<Integer>,
    }
}

diesel::table! {
    /// Representation of the `models` table.
    ///
    /// (Automatically generated by Diesel.)
    models (id) {
        /// The `id` column of the `models` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `city_id` column of the `models` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        city_id -> Nullable<Integer>,
        /// The `model_path` column of the `models` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        model_path -> Varchar,
        /// The `svg_id` column of the `models` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        svg_id -> Nullable<Integer>,
    }
}

diesel::table! {
    /// Representation of the `svgs` table.
    ///
    /// (Automatically generated by Diesel.)
    svgs (id) {
        /// The `id` column of the `svgs` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `city_id` column of the `svgs` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        city_id -> Nullable<Integer>,
        /// The `svg_path` column of the `svgs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        svg_path -> Varchar,
        /// The `image_id` column of the `svgs` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        image_id -> Nullable<Integer>,
        /// The `image_path` column of the `svgs` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        image_path -> Nullable<Varchar>,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        username -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Nullable<Varchar>,
        /// The `password_hash` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        password_hash -> Varchar,
        /// The `root_directory_path` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        root_directory_path -> Nullable<Varchar>,
        /// The `storage_quota` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bigint>`.
        ///
        /// (Automatically generated by Diesel.)
        storage_quota -> Nullable<Bigint>,
        /// The `storage_used` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Bigint>`.
        ///
        /// (Automatically generated by Diesel.)
        storage_used -> Nullable<Bigint>,
        /// The `access_level` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        access_level -> Nullable<Varchar>,
        /// The `encryption_key` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        encryption_key -> Nullable<Varchar>,
        /// The `last_access` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        last_access -> Nullable<Timestamp>,
    }
}

diesel::joinable!(cities -> users (user_id));
diesel::joinable!(models -> cities (city_id));
diesel::joinable!(svgs -> cities (city_id));

diesel::allow_tables_to_appear_in_same_query!(
    cities,
    files,
    images,
    models,
    svgs,
    users,
);
